# Generated by Django 4.2.4 on 2023-08-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('measurement_name', models.CharField(max_length=64, null=True)),
                ('measurement_unit', models.CharField(max_length=64, null=True)),
                ('realised_date', models.DateTimeField(auto_now=True)),
                ('edition_date', models.DateTimeField(null=True)),
                ('procedure', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
