# Generated by Django 4.2.4 on 2023-08-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab_journal_app', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_journal_app.method')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Lab_journal_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('analysis_date', models.DateField(auto_now=True)),
                ('methods', models.ManyToManyField(through='Lab_journal_app.Analysis', to='Lab_journal_app.method')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab_journal_app.sample'),
        ),
    ]
